#!/usr/bin/env python3
"""埋め込みフォント JailbreakMono-Regular.ttf を生成する。

HackGen Console Regular (v2.10.0, SIL OFL 1.1) を公式リリースから取得し、
ゲームが表示しうる文字だけにサブセット化したうえで、OFL の Reserved Font Name
("白源", "HackGen") を避けるためにフォント内部名を "JailbreakMono" に変更する。

使い方(リポジトリのルートで。通常は `make font` から呼ばれる):
    go run ./tools/fontchars > cmd/jailbreak-ebiten/fonts/chars.txt
    python3 tools/font/subset.py [--kanji used|jis1] [--src path/to/HackGenConsole-Regular.ttf]

必要なもの: Python 3 と fonttools (`pip install fonttools`)
"""

import argparse
import hashlib
import io
import os
import sys
import urllib.request
import zipfile

from fontTools import subset
from fontTools.ttLib import TTFont

HACKGEN_VERSION = "2.10.0"
HACKGEN_ZIP_URL = (
    f"https://github.com/yuru7/HackGen/releases/download/v{HACKGEN_VERSION}/"
    f"HackGen_v{HACKGEN_VERSION}.zip"
)
HACKGEN_ZIP_SHA256 = "ed182e2a4b95792d94dea7932f6b45280b5ae353651be249d5f6b7867b788db7"
HACKGEN_TTF_IN_ZIP = f"HackGen_v{HACKGEN_VERSION}/HackGenConsole-Regular.ttf"
HACKGEN_TTF_SHA256 = "72f550f90b49be633a9661f153b8c8398272785d9beda53dd5c400b61412a3ec"

CACHE_DIR = ".cache/fonts"
FONT_DIR = "cmd/jailbreak-ebiten/fonts"
CHARS_FILE = os.path.join(FONT_DIR, "chars.txt")
OUT_FILE = os.path.join(FONT_DIR, "JailbreakMono-Regular.ttf")

FAMILY = "JailbreakMono"
STYLE = "Regular"

# 実装から収集した文字(chars.txt)に加えて常に含める範囲。
# テキストを少し書き換えた程度で再生成が要らないよう、記号・かなは丸ごと入れる。
ALWAYS_RANGES = [
    (0x0020, 0x007E),  # ASCII 印字可能文字(タイピング入力・数字表示を含む)
    (0x00A0, 0x00FF),  # Latin-1 補助(×・÷・° 等)
    (0x2010, 0x2027),  # 一般句読点(‐ – — ‘ ’ “ ” … ‥ 等)
    (0x2030, 0x203B),  # ‰ ′ ″ ※ 等
    (0x2190, 0x21FF),  # 矢印
    (0x2200, 0x22FF),  # 数学記号(∧ ∪ ⊂ ⊃ 等。AA で使用)
    (0x2460, 0x24FF),  # 囲み英数字(① 等)
    (0x2500, 0x257F),  # 罫線
    (0x2580, 0x259F),  # ブロック要素
    (0x25A0, 0x25FF),  # 幾何学図形(■ □ ▲ △ ○ ● ◆ 等)
    (0x2600, 0x26FF),  # その他の記号(★ ☆ 等)
    (0x3000, 0x303F),  # CJK 記号と句読点(全角スペース・、。「」々 等)
    (0x3040, 0x309F),  # ひらがな
    (0x30A0, 0x30FF),  # カタカナ
    (0xFF01, 0xFF9F),  # 全角英数・記号、半角カナ
    (0xFFE0, 0xFFEE),  # 全角記号(￣ ￥ 等)
    (0x03B1, 0x03C9),  # ギリシャ小文字(ω は AA で使用)
    (0x0391, 0x03A9),  # ギリシャ大文字
]


def sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def load_source(src: str | None) -> bytes:
    """HackGen Console Regular の TTF を返す(未指定なら公式リリースから取得してキャッシュ)。"""
    if src:
        data = open(src, "rb").read()
    else:
        cached = os.path.join(CACHE_DIR, os.path.basename(HACKGEN_TTF_IN_ZIP))
        if os.path.exists(cached):
            data = open(cached, "rb").read()
        else:
            print(f"downloading {HACKGEN_ZIP_URL}", file=sys.stderr)
            with urllib.request.urlopen(HACKGEN_ZIP_URL) as r:
                z = r.read()
            if sha256(z) != HACKGEN_ZIP_SHA256:
                sys.exit(f"sha256 mismatch: {HACKGEN_ZIP_URL}")
            data = zipfile.ZipFile(io.BytesIO(z)).read(HACKGEN_TTF_IN_ZIP)
            os.makedirs(CACHE_DIR, exist_ok=True)
            open(cached, "wb").write(data)
    if sha256(data) != HACKGEN_TTF_SHA256:
        sys.exit("sha256 mismatch: HackGenConsole-Regular.ttf (v%s 以外が指定された?)" % HACKGEN_VERSION)
    return data


def jis_level1_kanji() -> set[int]:
    """JIS X 0208 第1水準漢字(16〜47区)のコードポイント集合。"""
    cps = set()
    for ku in range(16, 48):
        for ten in range(1, 95):
            try:
                ch = bytes([0xA0 + ku, 0xA0 + ten]).decode("euc_jp")
            except UnicodeDecodeError:
                continue
            cps.add(ord(ch))
    return cps


def build_unicodes(kanji: str) -> set[int]:
    cps = set()
    for lo, hi in ALWAYS_RANGES:
        cps.update(range(lo, hi + 1))
    text = open(CHARS_FILE, encoding="utf-8").read().rstrip("\n")
    cps.update(ord(c) for c in text)
    if kanji == "jis1":
        cps |= jis_level1_kanji()
    return cps


def rename(font: TTFont) -> None:
    """OFL の Reserved Font Name を避けるため、名前テーブルを JailbreakMono に置き換える。
    著作権表示(nameID 0)は元のまま残す。"""
    name = font["name"]
    full = f"{FAMILY} {STYLE}"
    ps = f"{FAMILY}-{STYLE}"
    # 優先ファミリ名等(16/17)や説明文は元の名前を含みうるので、著作権表示以外は消して作り直す
    name.names = [n for n in name.names if n.nameID == 0]
    for nid, value in {
        1: FAMILY,
        2: STYLE,
        3: f"{ps};{HACKGEN_VERSION}",
        4: full,
        5: f"Version {HACKGEN_VERSION}; subset for jailbreak-go",
        6: ps,
        10: (
            "Subset of HackGen Console Regular v%s by Yuko OTAWARA, renamed to "
            "comply with the Reserved Font Names of the SIL Open Font License 1.1. "
            "Generated by tools/font/subset.py of jailbreak-go." % HACKGEN_VERSION
        ),
        13: "This Font Software is licensed under the SIL Open Font License, Version 1.1.",
        14: "https://openfontlicense.org",
    }.items():
        name.setName(value, nid, 3, 1, 0x409)
    for n in name.names:
        s = n.toUnicode()
        if n.nameID not in (0, 10) and ("HackGen" in s or "白源" in s):
            sys.exit(f"name table still contains reserved name: {n.nameID} {s!r}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kanji", choices=["used", "jis1"], default="used",
                    help="漢字の収録方針: used=実装で使う漢字のみ(既定), jis1=JIS第1水準も追加")
    ap.add_argument("--src", help="HackGenConsole-Regular.ttf のパス(省略時は公式リリースから取得)")
    ap.add_argument("-o", "--output", default=OUT_FILE)
    args = ap.parse_args()

    # 再生成でバイナリが変わらないよう head.modified は元フォントの値のまま残す
    font = TTFont(io.BytesIO(load_source(args.src)), recalcTimestamp=False)
    cps = build_unicodes(args.kanji)

    opts = subset.Options()
    # Ebitengine(go-text)は TrueType ヒンティング命令を使わないので落とす
    opts.hinting = False
    opts.notdef_outline = True  # 未収録文字は豆腐(.notdef)として描かれる
    opts.name_IDs = ["*"]
    opts.name_languages = ["*"]
    opts.drop_tables += ["DSIG"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=cps)
    sub.subset(font)

    rename(font)
    font.save(args.output)
    cmap = font.getBestCmap()
    missing = [chr(c) for c in map(ord, open(CHARS_FILE, encoding="utf-8").read().rstrip("\n")) if c not in cmap]
    print(f"{args.output}: {os.path.getsize(args.output)} bytes, {len(cmap)} code points, kanji={args.kanji}",
          file=sys.stderr)
    if missing:
        print("WARNING: 元フォントに無い文字: " + "".join(missing), file=sys.stderr)


if __name__ == "__main__":
    main()
